### ISSUE TITLE
onStrengthChanged is not called if we paste the password using (command + v)

### ISSUE THREAD

**Issue by ggarg2** [angular-material-extensions/password-strength#129] opened 2018-12-27 19:17 UTC
Usecase is very simple. If you paste the password using command+v then progress-bar color is not changing it is still pink. Password is QwerT#123
`
<mat-password-strength #passwordComponent (onStrengthChanged)="onStrengthChanged($event)" [password]="passwordWithValidation?.value">
</mat-password-strength>

  
<mat-password-strength-info *ngIf="showPasswordDetails" 
[lowerCaseCriteriaMsg]="'Contains atleast one lower character'"
[upperCaseCriteriaMsg]="'contains at least one upper character'" 
[digitsCriteriaMsg]="'contains at least one digit character'"              
[specialCharsCriteriaMsg]="'contains at least one special character'" [minCharsCriteriaMsg]="'contains at least 8 characters'"             
[passwordComponent]="passwordComponent">
</mat-password-strength-info>
`
![screenshot 2018-12-28 at 12 45 10 am](https://user-images.githubusercontent.com/6575592/50491836-5ad80c00-0a3a-11e9-8e0f-5b7f36e28a4f.png)

**Comment by AnthonyNahas** [comment] 2018-12-28 08:42
@ggarg2 did you try that in the demo app too [here](https://angular-material-extensions.github.io/password-strength/) ?

I was not able to reproduce the bug (check below)

![ex 129_1](https://user-images.githubusercontent.com/20149774/50509001-e8dce280-0a8c-11e9-875c-69c3645d6fc2.gif)

**Comment by ggarg2** [comment] 2018-12-29 00:01
@AnthonyNahas I didn't try in demo. I am not using Angular Material fields. We are using Bootstrap 4.

**Comment by AnthonyNahas** [comment] 2018-12-29 13:45
Bootstrap is actually not supported... this library is implemented for angular material as extension.
However, I see that the developers are interested to use this library with bootstrap so I am planning to make it compatible with any input fields or progress bar component via an appropriate directive!

So tell me please what are the most important features that you need it from this library to use it in your bootstrap project!

Can you please provide a snippet of your code inc. the input fields (for debug purposes, since that is working normally with the material framework)

**Comment by AnthonyNahas** [comment] 2019-01-26 00:34
I will close the issue now. If you still have some troubles pls do not hesitate to reopen this

**Closed by AnthonyNahas** 2019-01-26 00:34 UTC
Labels: bug
