### ISSUE TITLE
mat-password-strength-info causing Javascript exception on iOS 15 Safari

### ISSUE THREAD

**Issue by anubhavnxpro** [angular-material-extensions/password-strength#339] opened 2021-10-06 11:46 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by DavidHedgesLogTag** [comment] 2022-01-11 01:45
dupe of #337?

**Comment by AnthonyNahas** [comment] 2022-06-21 20:47
please track #337

**Closed by AnthonyNahas** 2022-06-21 20:47 UTC
Labels: duplicate
